# Define stages of the pipeline
stages:
  - build
  - test
  - deploy

# Job for building the application
build:
  stage: build
  script:
    - echo "Building the application..."

# Job for running tests
test:
  stage: test
  script:
    - echo "Running tests..."

# Job for deploying the application
deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
